/*
 * Copyright © 2023 Github Lzhiyong
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package x.github.module.treesitter

import dalvik.annotation.optimization.CriticalNative
import dalvik.annotation.optimization.FastNative

import java.util.WeakHashMap

/**
 * A class that defines how to parse a particular language.
 *
 * When a [Language] is generated by the Tree-sitter CLI, it is assigned an
 * [ABI version][abiVersion] number that corresponds to the current CLI version.
 *
 * @constructor Create a new instance from the given language pointer.
 * @param language A pointer to a `TSLanguage` cast to [Long].
 * @throws [IllegalArgumentException]
 *  If the pointer is invalid or the [version][abiVersion] is incompatible.
 */
class TSLanguage internal constructor(val self: Long) {
    /**
     * Resolves or instantiates a tree-sitter language parsing library.
     * 
     * This operator interceptor eliminates JNI boundary crossing overhead by hitting a local 
     * cache when retrieving an actively loaded language definition.
     *
     * @param path The absolute path to the tree-sitter language shared library object (`.so`).
     * @param name The native export symbol name, typically formatted as `tree_sitter_c`, `tree_sitter_kotlin`, etc.
     * @return A thread-safe [TSLanguage] instance linked to the native parsing grammar.
     * 
     * #### Example
     * ```kotlin
     * val language = TSLanguage("/path/to/libtree_sitter_x.so", "tree_sitter_x")
     * ```
     */
    constructor(path: String, name: String): this(loadAndCache(path, name))
    
    init {
        if (self <= 0L) {
            throw IllegalArgumentException("Invalid language: $self")
        }
        checkVersion()
    }
    
    /**
     * The ABI version number for this language.
     *
     * @since 0.25.0
     */
    @get:JvmName("getAbiVersion")
    val abiVersion: UInt
        @FastNative external get
  
    /** The number of distinct node types in this language. */
    @get:JvmName("getSymbolCount")
    val symbolCount: UInt
        @FastNative external get
      
    @FastNative
    @Throws(IllegalArgumentException::class)
    private external fun checkVersion()
    
    /** The number of valid states in this language. */
    @get:JvmName("getStateCount")
    val stateCount: UInt
        @FastNative external get

    /** The number of distinct field names in this language. */
    @get:JvmName("getFieldCount")
    val fieldCount: UInt
        @FastNative external get
      
    /**
     * The name of the language, if available.
     *
     * @since 0.25.0
     */
    @get:JvmName("getName")
    val name: String?
        @FastNative external get

    /**
     * The metadata of the language, if available.
     *
     * @since 0.25.0
     */
    @get:JvmName("getMetadata")
    val metadata: Metadata?
        @FastNative external get
    
    /**
     * The supertype symbols of the language.
     *
     * @since 0.25.0
     */
    @OptIn(ExperimentalUnsignedTypes::class)
    @get:JvmName("getSupertypes")
    val supertypes: UShortArray
        @FastNative external get
        
    /**
     * Get the subtype symbols for the given supertype symbol
     *
     * @since 0.25.0
     * @see supertypes
     */
    @FastNative
    @JvmName("subtypes")
    @OptIn(ExperimentalUnsignedTypes::class)
    external fun subtypes(supertype: UShort): UShortArray
    
    /**
     * Get another reference to the language.
     *
     * @since 0.24.0
     */
    fun copy() = TSLanguage(copy(self))
    
    /** Get the node type for the given numerical ID. */
    @FastNative
    @JvmName("symbolName")
    external fun symbolName(symbol: UShort): String?
    
    /** Get the numerical ID for the given node type. */
    @FastNative
    @JvmName("symbolForName")
    external fun symbolForName(name: String, isNamed: Boolean): UShort
    
    /** Get the symbol type for the given symbol ID. */
    @FastNative
    @JvmName("symbolType")
    external fun symbolType(symbol: UShort): TSSymbolType
    
    /**
     * Check if the node for the given numerical ID is named
     *
     * @see [Node.isNamed]
     */
    @FastNative
    @JvmName("isNamed")
    external fun isNamed(symbol: UShort): Boolean

    /** Check if the node for the given numerical ID is visible. */
    @FastNative
    @JvmName("isVisible")
    external fun isVisible(symbol: UShort): Boolean
    
    /**
     * Check if the node for the given numerical ID is a supertype.
     *
     * @since 0.24.0
     */
    @FastNative
    @JvmName("isSupertype")
    external fun isSupertype(symbol: UShort): Boolean
    
    /** Get the field name for the given numerical id. */
    @FastNative
    @JvmName("fieldNameForId")
    external fun fieldNameForId(id: UShort): String?

    /** Get the numerical ID for the given field name. */
    @FastNative
    @JvmName("fieldIdForName")
    external fun fieldIdForName(name: String): UShort
    
    /**
     * Get the next parse state.
     *
     * Combine this with [lookaheadIterator] to generate
     * completion suggestions or valid symbols in error nodes.
     *
     * #### Example
     *
     * ```kotlin
     * language.nextState(node.parseState, node.grammarSymbol)
     * ```
     */
    @FastNative
    @JvmName("nextState")
    external fun nextState(state: UShort, symbol: UShort): UShort

    /**
     * Create a new [lookahead iterator][LookaheadIterator] for the given parse state.
     *
     * @throws [IllegalArgumentException] If the state is invalid for this language.
     */
    @JvmName("lookaheadIterator")
    @Throws(IllegalArgumentException::class)
    fun lookaheadIterator(state: UShort) = TSLookaheadIterator(this, state)
    
    override operator fun equals(other: Any?) =
        this === other || (other is TSLanguage && self == other.self)

    override fun hashCode() = self.hashCode()

    override fun toString() = "TSLanguage(id=0x${self.toString(16)}, version=$abiVersion)"
    
    /**
     * A class containing the [Language] metadata.
     *
     * @property semanticVersion The [Semantic Version](https://semver.org/) of the [Language].
     */
    @ConsistentCopyVisibility
    data class Metadata internal constructor(
        @get:JvmName("getSemanticVersion")
        val semanticVersion: Triple<UShort, UShort, UShort>
    ) {
        override fun toString() = buildString {
            append("Metadata(semanticVersion=\"")
            append(semanticVersion.first)
            append('.')
            append(semanticVersion.second)
            append('.')
            append(semanticVersion.third)
            append("\")")
        }
    }
    
    
    private companion object {
        /** note here requires load the native library */
        init {
            System.loadLibrary("android_tree_sitter")
        }
        
        /**
         * A composite key used to uniquely identify a loaded language library configuration
         * within the global memory cache.
         */
        private data class RefCache(val path: String, val name: String)
        
        /**
         * Global process-wide cache utilizing weak references. 
         * Once all external strong references to a [TSLanguage] instance are dropped, 
         * the garbage collector automatically discards the entry, preventing JVM memory leaks.
         */
        private val ptrCache = WeakHashMap<RefCache, Long>()
                
        fun loadAndCache(path: String, name: String): Long {
            val key = RefCache(path, name)
            synchronized(ptrCache) {
                // Return cached pointer if available to avoid redundant JNI operations
                ptrCache[key]?.let { return it }
                
                // Fallback to native dynamic loading on cache miss
                return load(path, name)
            }
        }
        
        @JvmStatic
        @CriticalNative
        private external fun copy(self: Long): Long
               
        @JvmStatic
        @FastNative
        private external fun unload(self: Long): Unit
        
        @JvmStatic
        private external fun load(path: String, name: String): Long
               
        @JvmStatic
        private external fun release(): Int
        
        @JvmStatic
        private external fun getLoadedCount(): Int
        
        @JvmStatic
        private external fun getUnusedCount(): Int
    }
}

